[package]
name = "tss-lib"
version = "0.6.0"
edition = "2018"
license = "GPL-3.0-or-later"
description = "Webassembly bindings to threshod signatures"


[workspace]
members = ["lindell17", "tss-eddsa", "wasm"]

[dependencies]
